defaults:
  - _self_
  - model: null
  - data: null
  - experiment/activation: null

optimizer:
  class_name: AdamW
  lr: 0.0005
  betas: [0.9, 0.999]
# optimizer:
#   class_name: SGD
#   lr: 0.0005
#   momentum: 0.9
# scheduler:
#   class_name: OneCycleLR
#   pct_start: 0.2
criterion:
  class_name: CrossEntropyLoss
compile:
  disable: true
  # fullgraph: false
  # dynamic: null
  # backend: inductor
  # mode: default
train:
  epochs: 100
  log_freq: 10
  forward_kwargs:
    loss_all_timesteps: false
  grad_clip:
    enable: false
    type: norm
    value: 1.0
checkpoint:
  load: false
  root: checkpoints/ei
  run: avid-disco-3472
  epoch: null
wandb:
  project: bioplnn
  mode: online
  group: null
activations:
  save_root: activations/ei
  save_activations: true
  num_samples: 10
  shuffle_test: true
seed: null
deterministic: false
tqdm: true
matmul_precision: high
debug_level: 0
debug_num_batches: null
